spring:
  application:
    name: user

server:
  port: 8888

say-hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: ec2-18-228-39-188.sa-east-1.compute.amazonaws.com:8080,ec2-18-228-39-188.sa-east-1.compute.amazonaws.com:8081,ec2-18-228-39-188.sa-east-1.compute.amazonaws.com:8082
    ServerListRefreshInterval: 15000
